/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sorting_algorithm_visualizer;

/**
 *
 * @author jackson
 */
public class code_visual_izer extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(code_visual_izer.class.getName());

    /**
     * Creates new form code_visual_izer
     */
    public code_visual_izer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleNameVisualizer = new javax.swing.JLabel();
        StepLabel = new javax.swing.JLabel();
        Stepx_1 = new javax.swing.JLabel();
        OfLabel = new javax.swing.JLabel();
        Stepy_2 = new javax.swing.JLabel();
        NextStep = new javax.swing.JButton();
        PreviousStep = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        FirstBox = new javax.swing.JLabel();
        SecondBox = new javax.swing.JLabel();
        ThirdBox = new javax.swing.JLabel();
        FourthBox = new javax.swing.JLabel();
        FithBox = new javax.swing.JLabel();
        HoldingBox = new javax.swing.JLabel();
        TenthBox = new javax.swing.JLabel();
        NinthBox = new javax.swing.JLabel();
        EighthBox = new javax.swing.JLabel();
        SeventhBox = new javax.swing.JLabel();
        SixthBox = new javax.swing.JLabel();
        Exit_Button = new javax.swing.JToggleButton();
        label1box = new javax.swing.JLabel();
        labelbox2 = new javax.swing.JLabel();
        labelbox3 = new javax.swing.JLabel();
        labelbox4 = new javax.swing.JLabel();
        labelbox5 = new javax.swing.JLabel();
        labelbox6 = new javax.swing.JLabel();
        labelbox7 = new javax.swing.JLabel();
        labelbox8 = new javax.swing.JLabel();
        labelbox9 = new javax.swing.JLabel();
        labelbox10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleNameVisualizer.setText("(Insert Sorting name here) Sorting");

        StepLabel.setText("Step");

        Stepx_1.setText("jLabel2");

        OfLabel.setText("of");

        Stepy_2.setText("jLabel4");

        NextStep.setText("Next");
        NextStep.addActionListener(this::NextStepActionPerformed);

        PreviousStep.setText("Prev");

        jTextField1.setText("Explaination");

        FirstBox.setText("Number1");

        SecondBox.setText("Number2");

        ThirdBox.setText("Number3");

        FourthBox.setText("Number4");

        FithBox.setText("Number5");

        HoldingBox.setText("Holding Box");

        TenthBox.setText("Number10");

        NinthBox.setText("Number9");

        EighthBox.setText("Number8");

        SeventhBox.setText("Number7");

        SixthBox.setText("Number6");

        Exit_Button.setText("Exit");

        label1box.setText("     1");

        labelbox2.setText("2");

        labelbox3.setText("3");

        labelbox4.setText("4");

        labelbox5.setText("jLabel5");

        labelbox6.setText("jLabel6");

        labelbox7.setText("jLabel7");

        labelbox8.setText("jLabel8");

        labelbox9.setText("jLabel9");

        labelbox10.setText("jLabel10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(TitleNameVisualizer))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(StepLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Stepx_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OfLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Stepy_2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(NextStep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PreviousStep))
                            .addComponent(Exit_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(HoldingBox)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstBox)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(label1box)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SecondBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(labelbox2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ThirdBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(labelbox3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(FourthBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(labelbox4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FithBox)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(labelbox5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(labelbox6))
                                    .addComponent(SixthBox))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SeventhBox)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(labelbox7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EighthBox)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(labelbox8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NinthBox)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(labelbox9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(labelbox10))
                            .addComponent(TenthBox))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleNameVisualizer)
                    .addComponent(StepLabel)
                    .addComponent(Stepx_1)
                    .addComponent(OfLabel)
                    .addComponent(Stepy_2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NextStep)
                            .addComponent(PreviousStep))
                        .addGap(18, 18, 18)
                        .addComponent(Exit_Button))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(HoldingBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SecondBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThirdBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FourthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FithBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SixthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeventhBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EighthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NinthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TenthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1box)
                    .addComponent(labelbox2)
                    .addComponent(labelbox3)
                    .addComponent(labelbox4)
                    .addComponent(labelbox5)
                    .addComponent(labelbox6)
                    .addComponent(labelbox7)
                    .addComponent(labelbox8)
                    .addComponent(labelbox9)
                    .addComponent(labelbox10))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NextStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextStepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NextStepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new code_visual_izer().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EighthBox;
    private javax.swing.JToggleButton Exit_Button;
    private javax.swing.JLabel FirstBox;
    private javax.swing.JLabel FithBox;
    private javax.swing.JLabel FourthBox;
    private javax.swing.JLabel HoldingBox;
    private javax.swing.JButton NextStep;
    private javax.swing.JLabel NinthBox;
    private javax.swing.JLabel OfLabel;
    private javax.swing.JButton PreviousStep;
    private javax.swing.JLabel SecondBox;
    private javax.swing.JLabel SeventhBox;
    private javax.swing.JLabel SixthBox;
    private javax.swing.JLabel StepLabel;
    private javax.swing.JLabel Stepx_1;
    private javax.swing.JLabel Stepy_2;
    private javax.swing.JLabel TenthBox;
    private javax.swing.JLabel ThirdBox;
    private javax.swing.JLabel TitleNameVisualizer;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label1box;
    private javax.swing.JLabel labelbox10;
    private javax.swing.JLabel labelbox2;
    private javax.swing.JLabel labelbox3;
    private javax.swing.JLabel labelbox4;
    private javax.swing.JLabel labelbox5;
    private javax.swing.JLabel labelbox6;
    private javax.swing.JLabel labelbox7;
    private javax.swing.JLabel labelbox8;
    private javax.swing.JLabel labelbox9;
    // End of variables declaration//GEN-END:variables







    //need selection, insertion, quicksort, bubblesort
    // have stops during to shows steps and explain how
    //need formula to calculate the total number of steps needed

    //exit button will trigger end of program

    //need to figure out how to implement "previous step" button









}
