
package sorting_algorithm_visualizer;
import java.utils.*;
import java.utils.Scanner;
/**
 *
 * @author jackson
 */
public class FirstFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FirstFrame.class.getName());

    /**
     * Creates new form FirstFrame
     */
    public FirstFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EnterNumbers = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        NumberInput = new javax.swing.JTextArea();
        SelectTextbox = new javax.swing.JLabel();
        InsertionToggle = new javax.swing.JToggleButton();
        SelectionToggle = new javax.swing.JToggleButton();
        QuickSortToggle = new javax.swing.JToggleButton();
        BubbleSorting = new javax.swing.JToggleButton();
        ErrorCodeMainMenu = new javax.swing.JLabel();
        Start = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EnterNumbers.setText("Enter your values below with a space between each number");

        NumberInput.setColumns(20);
        NumberInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NumberInput.setRows(5);
        NumberInput.setText("Example: 50 10 28 91 57 32");
        jScrollPane1.setViewportView(NumberInput);

        SelectTextbox.setText("Select a sorting option below");

        InsertionToggle.setText("Insertion");
        InsertionToggle.addActionListener(this::InsertionToggleActionPerformed);

        SelectionToggle.setText("Selection");
        SelectionToggle.addActionListener(this::SelectionToggleActionPerformed);

        QuickSortToggle.setText("Quick");
        QuickSortToggle.addActionListener(this::QuickSortToggleActionPerformed);

        BubbleSorting.setText("Bubble");
        BubbleSorting.addActionListener(this::BubbleSortingActionPerformed);

        ErrorCodeMainMenu.setText("ERROR CODE BOX");

        Start.setText("Start");
        Start.addActionListener(this::StartActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ErrorCodeMainMenu)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BubbleSorting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(QuickSortToggle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SelectionToggle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InsertionToggle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Start)))
                .addGap(253, 253, 253))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(EnterNumbers))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(SelectTextbox))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EnterNumbers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SelectTextbox)
                .addGap(18, 18, 18)
                .addComponent(InsertionToggle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SelectionToggle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuickSortToggle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BubbleSorting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(Start)
                .addGap(18, 18, 18)
                .addComponent(ErrorCodeMainMenu)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertionToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertionToggleActionPerformed
        
        
        
        
    }//GEN-LAST:event_InsertionToggleActionPerformed

    private void SelectionToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectionToggleActionPerformed



        // TODO add your handling code here:
    }//GEN-LAST:event_SelectionToggleActionPerformed

    private void QuickSortToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuickSortToggleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuickSortToggleActionPerformed

    private void BubbleSortingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BubbleSortingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BubbleSortingActionPerformed

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FirstFrame().setVisible(true));

//Action listeners
       // InsertionToggle.addActionListener(this);



    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BubbleSorting;
    private javax.swing.JLabel EnterNumbers;
    private javax.swing.JLabel ErrorCodeMainMenu;
    private javax.swing.JToggleButton InsertionToggle;
    private javax.swing.JTextArea NumberInput;
    private javax.swing.JToggleButton QuickSortToggle;
    private javax.swing.JLabel SelectTextbox;
    private javax.swing.JToggleButton SelectionToggle;
    private javax.swing.JButton Start;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public String SortingMethod = "";


    public void actionPerformed(ActionEvent e){
        //numClicks++;
        //text.setText("Button Clicked" +):
    }

public static void InputGet(){
boolean integrity = true;
    //sends to integrity checker, if return true proceed to inputset, if false then halt and display error


    //if return false
    if integrity == false {
        ErrorCodeMainMenu.setText("Input is invalid check input for errors");

    }
    else{
        //connect to InputSet here
    }

}
public static void InputSet(){
    
}

public static boolean InputIntegrityChecker(){
    //will return true or false
}

static void sortingMethodSetting(){    //Have error box display what sorting method has been choosen if at all
    // error box will stay blank until choosen



}

static void ExplatationTextbox(){

    //needs to look at steps that will follow and show the correct text from trigger
}



}
